
package test.hwj.client02.test.hwj.server02;

import test.hwj.server02.IHiService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HiServiceImplService", targetNamespace = "http://server02.hwj.test/", wsdlLocation = "http://127.0.0.1:9999/hi?wsdl")
public class HiServiceImplService
    extends Service
{

    private final static URL HISERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HISERVICEIMPLSERVICE_QNAME = new QName("http://server02.hwj.test/", "HiServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/hi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HISERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HiServiceImplService() {
        super(__getWsdlLocation(), HISERVICEIMPLSERVICE_QNAME);
    }

    public HiServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISERVICEIMPLSERVICE_QNAME, features);
    }

    public HiServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HISERVICEIMPLSERVICE_QNAME);
    }

    public HiServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISERVICEIMPLSERVICE_QNAME, features);
    }

    public HiServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HiServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHiService
     */
    @WebEndpoint(name = "HiServiceImplPort")
    public IHiService getHiServiceImplPort() {
        return super.getPort(new QName("http://server02.hwj.test/", "HiServiceImplPort"), IHiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHiService
     */
    @WebEndpoint(name = "HiServiceImplPort")
    public IHiService getHiServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server02.hwj.test/", "HiServiceImplPort"), IHiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HISERVICEIMPLSERVICE_EXCEPTION;
        }
        return HISERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
