
package test.hwj.client02.test.hwj.server02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHiService", targetNamespace = "http://server02.hwj.test/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHiService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server02.hwj.test/IHiService/sayHiRequest", output = "http://server02.hwj.test/IHiService/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
